spring:
  application:
    name: post-repeat
  redis:
    host: 10.3.117.43
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-idle: 300
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  mvc:
    static-path-pattern: /static/**
server:
  port: 8090