spring:
  http:
    encoding:
      charset: utf-8
      force: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml   #sql文件存放位置
  type-aliases-package: com.spring.web.entity
  global-config:
    #刷新mapper,调试神器
    db-config:
      id-type: auto  #0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      field-strategy: ignored #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      column-underline: true #驼峰下划线转换
      db-type: mysql
    refresh: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
