server:
  port: 18084
spring:
  application:
    name: sentinel-test
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
      datasource:
        ds:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow