server:
  port: 8081
spring:
  application:
    name: sentinel-test
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            ruleType: flow