server:
  port: 8081

spring:
  application:
    name: sc-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: path_route
          uri: http://cxytiandi.com
          predicates:
            - Path=/course
        - id: path3_route
          uri: http://cxytiandi.com
          predicates:
            - Path=/blog/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8171/eureka/