server:
  port: 8081

spring:
  application:
    name: sc-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: path_route  #id为Eureka注册的服务名
          uri: http://cxytiandi.com  #真正的服务地址
          predicates:
            - Path=/course   #请求路径
        - id: path3_route
          uri: http://cxytiandi.com
          predicates:
            - Path=/blog/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8171/eureka/