spring:
  application:
    name: sleuth-study
  sleuth:
    sampler:
      percentage: 1.0 #将采样比例1.0是全部都采集，默认是0.1
  zipkin:
    sender:
      type: web
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9005
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8171/eureka/
logging:
  level:
    org.springframework.web: DEBUG
  file: clould/${spring.application.name}.log
